Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String

Resources:
  MySecretManageAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SecretsManagerRead
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource:
              - arn:aws:secretsmanager:us-east-1:<aws-account-num>:secret:<secret-name>-*
              - arn:aws:secretsmanager:us-east-1:<aws-account-num>:secret:<secret-name>-*
              - arn:aws:secretsmanager:us-east-1:<aws-account-num>:secret:<secret-name>-*

Outputs:
  MySecretManageAccessPolicyArn:
    Description: "The ARN of the ManagedPolicy to attach to the task role."
    Value: !Ref MySecretManageAccessPolicy